{
 "title": "LOAD BALANCER",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "AWS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase (requests_total{instance=~\"aws.*\"}[$interval]) or up{instance=~\"aws.*\"}",
     "legendFormat": "AWS"
    }
   ]
  },
  {
   "title": "DIVEO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase (requests_total{instance=~\"diveo.*\"}[$interval]) or up{instance=~\"diveo.*\"}",
     "legendFormat": "AWS"
    }
   ]
  },
  {
   "title": "VIVO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase (requests_total{instance=~\"vivo.*\"}[$interval]) or up{instance=~\"vivo.*\"}",
     "legendFormat": "VIVO"
    }
   ]
  },
  {
   "title": "% Requisicoes",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "(sum(increase (requests_total{instance=~\"aws.*\"}[$interval])) / sum(increase (requests_total[$interval])) * 100 > 0) or increase(requests_total{instance=~\"aws.*\"}[$interval]) == 0",
     "legendFormat": "AWS"
    },
    {
     "expr": "(sum(increase (requests_total{instance=~\"diveo.*\"}[$interval])) / sum(increase (requests_total[$interval])) * 100 > 0) or increase(requests_total{instance=~\"diveo.*\"}[$interval]) == 0",
     "legendFormat": "DIVEO"
    },
    {
     "expr": "(sum(increase (requests_total{instance=~\"vivo.*\"}[$interval])) / sum(increase (requests_total[$interval])) * 100 > 0) or increase(requests_total{instance=~\"vivo.*\"}[$interval]) == 0",
     "legendFormat": "VIVO"
    }
   ]
  }
 ]
}