version: "3.7"
services:
  vivo:
    image: willianvalerio/ginger-app
    ports: 
      - 82:8080
    networks:
      - rede
  diveo:
    image: willianvalerio/ginger-app
    ports: 
      - 83:8080
    networks:
      - rede
  aws:
    image: willianvalerio/ginger-app
    ports: 
      - 81:8080
    networks:
      - rede
  lb:
    image: nginx
    volumes:
      - ./lb.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80
    networks:
      - rede
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/var/lib/prometheus
    ports:
      - 9090:9090
    networks:
      - rede
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    env_file:
      - grafana/grafana.ini
    depends_on:
      - prometheus
    networks:
      - rede
    ports:
      - 3000:3000
     
networks:
  rede:
volumes:
  prometheus_data: