version: "3.7"
services:
  vivo:
    image: registry.gitlab.com/tecninjas/ginger/gitlabxaws:5c4fbc96
    ports: 
      - 82:8080
    networks:
      - rede
  diveo:
    image: registry.gitlab.com/tecninjas/ginger/gitlabxaws:5c4fbc96
    ports: 
      - 83:8080
    networks:
      - rede
  aws:
    image: registry.gitlab.com/tecninjas/ginger/gitlabxaws:5c4fbc96
    ports: 
      - 81:8080
    networks:
      - rede
  lb:
    image: nginx
    volumes:
      - ./lb.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80
    networks:
      - rede
  prometheus:
    image: linuxtips/prometheus_alpine
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/var/lib/prometheus
    ports:
      - 9090:9090
    networks:
      - rede
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - rede
    ports:
      - 3000:3000
     
networks:
  rede:
volumes:
  prometheus_data:
  grafana_data:
